---
- hosts: localhost
  become: true
  tasks:
    - name: install dependencies
      apt:
        pkg:
          - r-base
    - name: Install rstudio
      apt:
        deb: https://download2.rstudio.org/server/trusty/amd64/rstudio-server-1.2.5033-amd64.deb
    
    - name: Create systemd file
      copy:
        content: |
          [Unit]
          Description=RStudio Server for Codio
          Wants=network-online.target
          After=network-online.target

          [Service]
          Type=simple
          User=codio
          Group=codio
          WorkingDirectory=/home/codio/workspace
          ExecStartPre=/bin/rm -rf /home/codio/.rstudio/sessions/active
          ExecStart=/usr/lib/rstudio-server/bin/rserver --server-daemonize=0 --auth-none=1
          #ExecStop=/usr/bin/killall -TERM rserver
          #KillMode=none
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/rstudio-server-codio.service
        group: root
        owner: root
        mode: 0644
        
    - name: enable hue
      systemd:
        name: rstudio-server-codio
        enabled: yes
        masked: no
        state: started
